---
- name: Configure EC2 instances
  hosts: tag_Project_anxiousbot
  become: yes
  vars_files:
    - vars/secrets.yml

  tasks:
    - name: Ping EC2 instances
      ping:

    - name: Update all packages on Amazon Linux
      yum:
        name: '*'
        state: latest

    - name: Install required system packages
      yum:
        name:
          - git
          - python3.11
          - python3.11-pip
          - amazon-cloudwatch-agent
        state: latest

    - name: Install Poetry
      pip:
        name: poetry
        executable: pip3.11
        extra_args: --ignore-installed

    - name: Create CloudWatch Agent configuration directory
      file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: '0755'

    - name: Create logs directory
      file:
        path: /var/log/anxiousbot
        state: directory
        mode: '0755'

    - name: Create CloudWatch Agent configuration file
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "root"
            },
            "metrics": {
              "append_dimensions": {
                "InstanceId": "${aws:InstanceId}"
              },
              "metrics_collected": {
                "cpu": {
                  "measurement": [
                    "cpu_usage_idle",
                    "cpu_usage_iowait",
                    "cpu_usage_user",
                    "cpu_usage_system"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "*"
                  ]
                },
                "mem": {
                  "measurement": [
                    "mem_used_percent"
                  ],
                  "metrics_collection_interval": 60
                },
                "net": {
                  "measurement": [
                    "bytes_sent",
                    "bytes_recv"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "*"
                  ]
                }
              }
            },
            "logs": {
              "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/anxiousbot/*.log",
                      "log_group_name": "anxiousbot-logs",
                      "log_stream_name": "{instance_id}-messages",
                      "timezone": "UTC"
                    }
                  ]
                }
              },
              "log_stream_name": "anxiousbot_log_stream"
            }
          }

    - name: Clone the GitHub repository
      git:
        repo: 'https://{{ github_token }}@github.com/fmenezes/anxiousbot.git'
        dest: /opt/anxiousbot

    - name: Install dependencies with Poetry
      shell: |
        cd /opt/anxiousbot
        poetry install
      args:
        executable: /bin/bash

    - name: Copy systemd service file
      copy:
        src: anxiousbot.service
        dest: /etc/systemd/system/anxiousbot.service
        owner: root
        group: root
        mode: 0644

    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start CloudWatch Agent service
      systemd:
        name: amazon-cloudwatch-agent
        enabled: yes
        state: started

    - name: Enable and start Anxiousbot Service
      systemd:
        name: anxiousbot
        state: started
        enabled: yes
