---
- name: Configure EC2 instances
  hosts: tag_Project_anxiousbot
  become: yes
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Ping EC2 instances
      ping:

    - name: Update all packages on Amazon Linux
      yum:
        name: '*'
        state: latest

    - name: Install CloudWatch Agent
      yum:
        name: amazon-cloudwatch-agent
        state: present

    - name: Create CloudWatch Agent configuration directory
      file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: '0755'

    - name: Create CloudWatch Agent configuration file
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "root"
            },
            "metrics": {
              "append_dimensions": {
                "InstanceId": "${aws:InstanceId}"
              },
              "metrics_collected": {
                "cpu": {
                  "measurement": [
                    "cpu_usage_idle",
                    "cpu_usage_iowait",
                    "cpu_usage_user",
                    "cpu_usage_system"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "*"
                  ]
                },
                "mem": {
                  "measurement": [
                    "mem_used_percent"
                  ],
                  "metrics_collection_interval": 60
                },
                "net": {
                  "measurement": [
                    "bytes_sent",
                    "bytes_recv"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "*"
                  ]
                }
              }
            },
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/messages",
                      "log_group_name": "anxiousbot-logs",
                      "log_stream_name": "{instance_id}-messages",
                      "timezone": "UTC"
                    },
                    {
                      "file_path": "/var/log/secure",
                      "log_group_name": "anxiousbot-logs",
                      "log_stream_name": "{instance_id}-secure",
                      "timezone": "UTC"
                    }
                  ]
                }
              },
              "log_stream_name": "my_log_stream_name"
            }
          }

    - name: Start CloudWatch Agent
      command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s
      args:
        creates: /opt/aws/amazon-cloudwatch-agent/var/amazon-cloudwatch-agent.log
