name: Deploy Infrastructure

on:
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5  # Adjust to your required version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init

      - run: terraform import aws_s3_bucket.main anxiousbot-main-bucket

      - run: terraform apply -auto-approve

  ansible:
    runs-on: ubuntu-latest
    needs: 
      - terraform
    defaults:
      run:
        working-directory: ./deploy/ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - run: /opt/pipx/venvs/ansible-core/bin/pip install botocore boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: echo "${{ secrets.VAULT_PASS }}" > .vault_pass

      - run: ansible-playbook playbook-setup.yml
