name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'  # Adjust to the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build
      env:
        ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        NODE_ENV: production

    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist/'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
